name: sendgo_flutter
description: Sendgo Flutter SDK — 카카오 알림톡/친구톡, SMS/LMS/MMS
version: 1.0.1
homepage: https://sendgo.io
repository: https://github.com/sendgo-dev/sendgo-flutter

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
